// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package api

import (
	"context"
	"github.com/iudanet/gophkeeper/pkg/api"
	"sync"
)

// Ensure, that ClientAPIMock does implement ClientAPI.
// If this is not the case, regenerate this file with moq.
var _ ClientAPI = &ClientAPIMock{}

// ClientAPIMock is a mock implementation of ClientAPI.
//
//	func TestSomethingThatUsesClientAPI(t *testing.T) {
//
//		// make and configure a mocked ClientAPI
//		mockedClientAPI := &ClientAPIMock{
//			GetSaltFunc: func(ctx context.Context, username string) (*api.SaltResponse, error) {
//				panic("mock out the GetSalt method")
//			},
//			LoginFunc: func(ctx context.Context, req api.LoginRequest) (*api.TokenResponse, error) {
//				panic("mock out the Login method")
//			},
//			LogoutFunc: func(ctx context.Context, accessToken string) error {
//				panic("mock out the Logout method")
//			},
//			RefreshFunc: func(ctx context.Context, refreshToken string) (*api.TokenResponse, error) {
//				panic("mock out the Refresh method")
//			},
//			RegisterFunc: func(ctx context.Context, req api.RegisterRequest) (*api.RegisterResponse, error) {
//				panic("mock out the Register method")
//			},
//			SyncFunc: func(ctx context.Context, accessToken string, req api.SyncRequest) (*api.SyncResponse, error) {
//				panic("mock out the Sync method")
//			},
//		}
//
//		// use mockedClientAPI in code that requires ClientAPI
//		// and then make assertions.
//
//	}
type ClientAPIMock struct {
	// GetSaltFunc mocks the GetSalt method.
	GetSaltFunc func(ctx context.Context, username string) (*api.SaltResponse, error)

	// LoginFunc mocks the Login method.
	LoginFunc func(ctx context.Context, req api.LoginRequest) (*api.TokenResponse, error)

	// LogoutFunc mocks the Logout method.
	LogoutFunc func(ctx context.Context, accessToken string) error

	// RefreshFunc mocks the Refresh method.
	RefreshFunc func(ctx context.Context, refreshToken string) (*api.TokenResponse, error)

	// RegisterFunc mocks the Register method.
	RegisterFunc func(ctx context.Context, req api.RegisterRequest) (*api.RegisterResponse, error)

	// SyncFunc mocks the Sync method.
	SyncFunc func(ctx context.Context, accessToken string, req api.SyncRequest) (*api.SyncResponse, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetSalt holds details about calls to the GetSalt method.
		GetSalt []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Username is the username argument value.
			Username string
		}
		// Login holds details about calls to the Login method.
		Login []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req api.LoginRequest
		}
		// Logout holds details about calls to the Logout method.
		Logout []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AccessToken is the accessToken argument value.
			AccessToken string
		}
		// Refresh holds details about calls to the Refresh method.
		Refresh []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RefreshToken is the refreshToken argument value.
			RefreshToken string
		}
		// Register holds details about calls to the Register method.
		Register []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req api.RegisterRequest
		}
		// Sync holds details about calls to the Sync method.
		Sync []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AccessToken is the accessToken argument value.
			AccessToken string
			// Req is the req argument value.
			Req api.SyncRequest
		}
	}
	lockGetSalt  sync.RWMutex
	lockLogin    sync.RWMutex
	lockLogout   sync.RWMutex
	lockRefresh  sync.RWMutex
	lockRegister sync.RWMutex
	lockSync     sync.RWMutex
}

// GetSalt calls GetSaltFunc.
func (mock *ClientAPIMock) GetSalt(ctx context.Context, username string) (*api.SaltResponse, error) {
	if mock.GetSaltFunc == nil {
		panic("ClientAPIMock.GetSaltFunc: method is nil but ClientAPI.GetSalt was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Username string
	}{
		Ctx:      ctx,
		Username: username,
	}
	mock.lockGetSalt.Lock()
	mock.calls.GetSalt = append(mock.calls.GetSalt, callInfo)
	mock.lockGetSalt.Unlock()
	return mock.GetSaltFunc(ctx, username)
}

// GetSaltCalls gets all the calls that were made to GetSalt.
// Check the length with:
//
//	len(mockedClientAPI.GetSaltCalls())
func (mock *ClientAPIMock) GetSaltCalls() []struct {
	Ctx      context.Context
	Username string
} {
	var calls []struct {
		Ctx      context.Context
		Username string
	}
	mock.lockGetSalt.RLock()
	calls = mock.calls.GetSalt
	mock.lockGetSalt.RUnlock()
	return calls
}

// Login calls LoginFunc.
func (mock *ClientAPIMock) Login(ctx context.Context, req api.LoginRequest) (*api.TokenResponse, error) {
	if mock.LoginFunc == nil {
		panic("ClientAPIMock.LoginFunc: method is nil but ClientAPI.Login was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req api.LoginRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockLogin.Lock()
	mock.calls.Login = append(mock.calls.Login, callInfo)
	mock.lockLogin.Unlock()
	return mock.LoginFunc(ctx, req)
}

// LoginCalls gets all the calls that were made to Login.
// Check the length with:
//
//	len(mockedClientAPI.LoginCalls())
func (mock *ClientAPIMock) LoginCalls() []struct {
	Ctx context.Context
	Req api.LoginRequest
} {
	var calls []struct {
		Ctx context.Context
		Req api.LoginRequest
	}
	mock.lockLogin.RLock()
	calls = mock.calls.Login
	mock.lockLogin.RUnlock()
	return calls
}

// Logout calls LogoutFunc.
func (mock *ClientAPIMock) Logout(ctx context.Context, accessToken string) error {
	if mock.LogoutFunc == nil {
		panic("ClientAPIMock.LogoutFunc: method is nil but ClientAPI.Logout was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		AccessToken string
	}{
		Ctx:         ctx,
		AccessToken: accessToken,
	}
	mock.lockLogout.Lock()
	mock.calls.Logout = append(mock.calls.Logout, callInfo)
	mock.lockLogout.Unlock()
	return mock.LogoutFunc(ctx, accessToken)
}

// LogoutCalls gets all the calls that were made to Logout.
// Check the length with:
//
//	len(mockedClientAPI.LogoutCalls())
func (mock *ClientAPIMock) LogoutCalls() []struct {
	Ctx         context.Context
	AccessToken string
} {
	var calls []struct {
		Ctx         context.Context
		AccessToken string
	}
	mock.lockLogout.RLock()
	calls = mock.calls.Logout
	mock.lockLogout.RUnlock()
	return calls
}

// Refresh calls RefreshFunc.
func (mock *ClientAPIMock) Refresh(ctx context.Context, refreshToken string) (*api.TokenResponse, error) {
	if mock.RefreshFunc == nil {
		panic("ClientAPIMock.RefreshFunc: method is nil but ClientAPI.Refresh was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		RefreshToken string
	}{
		Ctx:          ctx,
		RefreshToken: refreshToken,
	}
	mock.lockRefresh.Lock()
	mock.calls.Refresh = append(mock.calls.Refresh, callInfo)
	mock.lockRefresh.Unlock()
	return mock.RefreshFunc(ctx, refreshToken)
}

// RefreshCalls gets all the calls that were made to Refresh.
// Check the length with:
//
//	len(mockedClientAPI.RefreshCalls())
func (mock *ClientAPIMock) RefreshCalls() []struct {
	Ctx          context.Context
	RefreshToken string
} {
	var calls []struct {
		Ctx          context.Context
		RefreshToken string
	}
	mock.lockRefresh.RLock()
	calls = mock.calls.Refresh
	mock.lockRefresh.RUnlock()
	return calls
}

// Register calls RegisterFunc.
func (mock *ClientAPIMock) Register(ctx context.Context, req api.RegisterRequest) (*api.RegisterResponse, error) {
	if mock.RegisterFunc == nil {
		panic("ClientAPIMock.RegisterFunc: method is nil but ClientAPI.Register was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req api.RegisterRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockRegister.Lock()
	mock.calls.Register = append(mock.calls.Register, callInfo)
	mock.lockRegister.Unlock()
	return mock.RegisterFunc(ctx, req)
}

// RegisterCalls gets all the calls that were made to Register.
// Check the length with:
//
//	len(mockedClientAPI.RegisterCalls())
func (mock *ClientAPIMock) RegisterCalls() []struct {
	Ctx context.Context
	Req api.RegisterRequest
} {
	var calls []struct {
		Ctx context.Context
		Req api.RegisterRequest
	}
	mock.lockRegister.RLock()
	calls = mock.calls.Register
	mock.lockRegister.RUnlock()
	return calls
}

// Sync calls SyncFunc.
func (mock *ClientAPIMock) Sync(ctx context.Context, accessToken string, req api.SyncRequest) (*api.SyncResponse, error) {
	if mock.SyncFunc == nil {
		panic("ClientAPIMock.SyncFunc: method is nil but ClientAPI.Sync was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		AccessToken string
		Req         api.SyncRequest
	}{
		Ctx:         ctx,
		AccessToken: accessToken,
		Req:         req,
	}
	mock.lockSync.Lock()
	mock.calls.Sync = append(mock.calls.Sync, callInfo)
	mock.lockSync.Unlock()
	return mock.SyncFunc(ctx, accessToken, req)
}

// SyncCalls gets all the calls that were made to Sync.
// Check the length with:
//
//	len(mockedClientAPI.SyncCalls())
func (mock *ClientAPIMock) SyncCalls() []struct {
	Ctx         context.Context
	AccessToken string
	Req         api.SyncRequest
} {
	var calls []struct {
		Ctx         context.Context
		AccessToken string
		Req         api.SyncRequest
	}
	mock.lockSync.RLock()
	calls = mock.calls.Sync
	mock.lockSync.RUnlock()
	return calls
}
